M48
; DRILL file {KiCad 9.0.4-9.0.4-0~ubuntu22.04.1} date 2025-10-27T10:48:21-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-27T10:48:21-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4-9.0.4-0~ubuntu22.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.025
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C3.100
%
G90
G05
T1
X142.0Y-74.8
T2
X130.0Y-70.0
X154.0Y-70.0
M30
